name: Format Kode

on:
  pull_request:
    paths:
      - "donjo-app/Views/**"
  # pull_request_review:
    # types: [submitted]

jobs:
  beautifier:
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - run: npm ci
      - id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: donjo-app/Views/**
      - if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          for i in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
          npm run format $i
          done
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format View
