name: Fixer, Styling & Optimizer

on: [workflow_dispatch]

permissions:
  actions: write
  contents: write
  pull-requests: write

jobs:
  php-cs-fixer:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: composer install
      - run: composer run csfix
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fixed & optimize code
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
 
