name: PHP-CS-FIXER

on: 
  pull_request:
    paths:
      - "**.php"
      - "!donjo-app/Views/**"
      - "!donjo-app/Libraries/**"
      - "!donjo-app/third_party/**"

permissions:
  contents: read

jobs:
  fix:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0']
        paths:
          - donjo-app
        
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl
      - run: composer install --ansi --no-interaction
      - run: donjo-sys/bin/rector process ${{ matrix.paths }} --dry-run --no-progress-bar
      - run: donjo-sys/bin/php-cs-fixer fix --verbose --ansi --dry-run --using-cache=no --diff 
